### ISSUE TITLE
Demo Project: Incomplete Reply

### ISSUE THREAD

**Issue by Schneppi** [charonn0/Xojo-OpenAI#2]
Using the **Demo Project**, if i use a german spelled natural language prompt, **the reply is incomplete**.

As an example, try to enter **the prompt**: "_Welchen Öffnungswinkel erreichen WLAN Antennen?_"

**The Reply** will show something like "

_Der Öffnungswinkel einer WLAN-Antenne hängt von der Art der Antenne ab. Für Richtantennen liegt er normalerweise zwischen 30 und 60 Grad, während Sektor- oder Yagi-_"

As we can see, it stops after "Yagi-", but the complete reply must be more.

**Comment by charonn0** [comment]
Try increasing the token count for the request. The default is 64 tokens, but it looks like that reply consumes 62 tokens (see: [token count estimator](https://platform.openai.com/tokenizer)). 128 tokens will probably be enough.

Note that the API charges by token count ($0.02/ 1K tokens for the `davinci` text completion model.)

https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them
